# -*- coding: utf-8 -*-
"""hw10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dlmxyS-BsTvgx1M0QTU8GgIdyEiTT_O8
"""

import pickle

def input_scores():
    scores = []
    i = 1
    while True:
        score = int(input(f"#{i}? "))
        if score < 0:
            break
        scores.append(score)
        i += 1
    return scores

def get_average(scores):
    return sum(scores) / len(scores) if scores else 0

def show_scores(scores):
    print("[점수 출력]")
    print("개인점수:", " ".join(map(str, scores)))
    print(f"평균: {get_average(scores):.1f}")

def save_scores(scores, filename="score.bin"):
    with open(filename, "wb") as file:
        pickle.dump(scores, file)

def load_scores(filename="score.bin"):
    try:
        with open(filename, "rb") as file:
            return pickle.load(file)
    except FileNotFoundError:
        return None

print("[파일 읽기]")
scores = load_scores()

if scores is None:
    print("[점수 입력]")
    scores = input_scores()
    save_scores(scores)

show_scores(scores)