# -*- coding: utf-8 -*-
"""hw2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gvr6ecbvx5A1CjMkcHBqfQYkyClUaGoZ
"""

def get_integer():
    n = int(input("동전으로 교환하고자 하는 금액은? "))
    return n

def exchange(amount):
    count_500 = amount // 500
    amount %= 500
    print("500원 동전의 개수:", count_500)

    count_100 = amount // 100
    amount %= 100
    print("100원 동전의 개수:", count_100)

    count_50 = amount // 50
    amount %= 50
    print("50원 동전의 개수:", count_50)

    count_10 = amount // 10
    amount %= 10
    print("10원 동전의 개수:", count_10)

amount = get_integer()
exchange(amount)