# -*- coding: utf-8 -*-
"""hw4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJm1pwhKT_fsic22jr9-jVcWdtgguF9A
"""

def rep_char(c, n):
    print(c * n)

def draw_welcome_message(name):
    msg1 = f"Hello {name},"
    msg2 = "Welcome to Seoul."

    nstr = len(msg1) if len(msg1) > len(msg2) else len(msg2)

    rep_char('-', nstr)
    print(msg1)
    print(msg2)
    rep_char('-', nstr)

name = input("Input his/her name: ")
draw_welcome_message(name)