# -*- coding: utf-8 -*-
"""hw5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nfwZZHaBtWqAho_hF_UnFFr5o-QBl2xf
"""

def read_single_digit(digit):
    korean_digits = ["영", "일", "이", "삼", "사", "오", "육", "칠", "팔", "구"]
    return korean_digits[digit]

def read_number(number):
    if number < 10:
        return read_single_digit(number)
    return read_number(number // 10) + " " + read_single_digit(number % 10)

def main():
    user_input = input("세자리 정수 입력: ")
    if int(user_input) > 999 or int(user_input) < 0:
        print("유효하지 않은 입력입니다. 0에서 999 사이의 숫자를 입력해주세요.")
        return

    number = int(user_input)
    print(read_number(number))

if __name__ == "__main__":
    main()