# -*- coding: utf-8 -*-
"""hw6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mgpp7YMHEaKCYd5Bvg6ax5153VW6M5-X
"""

for i in range(1, 10):
    for j in range(2, 6):
        print(f"{j} x {i} = {j * i}", end="\t")
    print()

print()

for i in range(1, 10):
    for j in range(6, 10):
        print(f"{j} x {i} = {j * i}", end="\t")
    print()