# -*- coding: utf-8 -*-
"""hw7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQvGvCJyOaBAh4eVAzNO0n9QTZC-wslo
"""

shopping_bag = {}

while True:
    item = input("상품명? ")

    if item == "":
        break

    quantity = int(input("수량은? "))

    shopping_bag[item] = shopping_bag.get(item, 0) + quantity
    print(f"장바구니에 {item} {quantity}개가 담겼습니다.")


print(f">>> 장바구니 보기: {shopping_bag}")