# -*- coding: utf-8 -*-
"""hw8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13sn3TMKER197p3jsdhU-18-F991K6VI0
"""

def buy(shopping_bag):
    item = input("[구입]\n상품명? ")
    if item == "":
        return False

    quantity = int(input("수량은? "))
    shopping_bag[item] = shopping_bag.get(item, 0) + quantity
    print(f"장바구니에 {item} {quantity}개가 담겼습니다.")
    return True

def show(shopping_bag):
    print(f">>> 장바구니 보기: {shopping_bag}")

def find(shopping_bag):
    search_item = input("[검색]\n장바구니에서 확인하고자 하는 상품은? ")
    if search_item in shopping_bag:
        print(f"{search_item}(은)는 {shopping_bag[search_item]}개 담겨 있습니다.")
    else:
        print(f"장바구니에 {search_item}(은)는 없습니다.")

shopping_bag = {}

while True:
    if not buy(shopping_bag):
        break
    show(shopping_bag)
    find(shopping_bag)